### PR TITLE
refactor: use Option.map to simplify match expressions

### PR DESCRIPTION
**Pull request by Yag000**
I saw two functions that could be simplified by using `Option.map`. 

For `play_move` I also simplified the `fifty_rule` update

### CODE REVIEW

**Comment by ThomArr** [comment]
Thank you very much

**Comment by ThomArr** [comment]
Good evening @Yag000,
Ha yes thank you very much! It is true that I do not know "Option.map" well. I think I can do it in other places. But since you didn’t offer them. I don’t know if you just didn’t see them. Or if you think it would complicate the code too much. So I’ll ask you. Do you think I should do the same in the "get_starter_piece", "move_from_coord_to_coord", "chess_mate" and "play_move" functions? 
Have a nice evening,
Thomas

**Comment by Yag000** [comment]
> Good evening @Yag000,
> Ha yes thank you very much! It is true that I do not know "Option.map" well. I think I can do it in other places. But since you didn’t offer them. I don’t know if you just didn’t see them. Or if you think it would complicate the code too much. So I’ll ask you. Do you think I should do the same in the "get_starter_piece", "move_from_coord_to_coord", "chess_mate" and "play_move" functions?
> Have a nice evening, 
> Thomas

- `get_starter_piece` uses only pattern matching on a double `option` which makes using `map` pretty hard and less readable.
- For `move_from_coord_to_coord` it is doable and I've committed a proposal for that, fell free to reject it: b8f49801b294a59f485a36e0f534025b24b18722
- Same for `chess_mate`: b7062a4f711b18339e6ef983ad5b9edd71d9bdec (this function desperately needs some refactoring, but it is a bit more tricky to do, I'd rather wait for tests to be written before touching that)
-  `play_move` has room for that, but in most matches it is impossible since you can also return `None` on the `Some` branches, so the map is not available there, since this is the definition of `map`: 
```ocaml
val map : ('a -> 'b) -> 'a option -> 'b option
```

**Review by ThomArr — APPROVED** [review]

**Comment by ThomArr** [comment]
Ok thank you very much for all her information!
Good evening

**Pull request merged**
